<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('districts')->delete();
        $districts = array(
            array('state_id' => 26, 'name' => "Ariyalur",'code' => "AR"),
            array('state_id' => 26, 'name' => "Chengalpattu",'code' => "CP"),
            array('state_id' => 26, 'name' => "Chennai",'code' => "CH"),
            array('state_id' => 26, 'name' => "Coimbatore",'code' => "CB"),
            array('state_id' => 26, 'name' => "Cuddalore",'code' => "CD"),
            array('state_id' => 26, 'name' => "Dharmapuri",'code' => "DP"),
            array('state_id' => 26, 'name' => "Dindigul",'code' => "DK"),
            array('state_id' => 26, 'name' => "Erode",'code' => "ER"),
            array('state_id' => 26, 'name' => "Kallakurichi",'code' => "KK"),
            array('state_id' => 26, 'name' => "Kanchipuram",'code' => "KP"),
            array('state_id' => 26, 'name' => "Kanyakumari",'code' => "KY"),
            array('state_id' => 26, 'name' => "Karur",'code' => "KR"),
            array('state_id' => 26, 'name' => "Krishnagiri",'code' => "KG"),
            array('state_id' => 26, 'name' => "Madurai",'code' => "MD"),
            array('state_id' => 26, 'name' => "Nagapattinam",'code' => "NP"),
            array('state_id' => 26, 'name' => "Namakkal",'code' => "NK"),
            array('state_id' => 26, 'name' => "Nilgiris",'code' => "NL"),
            array('state_id' => 26, 'name' => "Perambalur",'code' => "PR"),
            array('state_id' => 26, 'name' => "Pudukkottai",'code' => "PD"),
            array('state_id' => 26, 'name' => "Ramanathapuram",'code' => "RM"),
            array('state_id' => 26, 'name' => "Ranipet",'code' => "RP"),
            array('state_id' => 26, 'name' => "Salem",'code' => "SE"),
            array('state_id' => 26, 'name' => "Sivaganga",'code' => "SG"),
            array('state_id' => 26, 'name' => "Tenkasi",'code' => "TK"),
            array('state_id' => 26, 'name' => "Thanjavur",'code' => "TJ"),
            array('state_id' => 26, 'name' => "Theni",'code' => "TH"),
            array('state_id' => 26, 'name' => "Thoothukudi (Tuticorin)",'code' => "TH"),
            array('state_id' => 26, 'name' => "Tiruchirappalli",'code' => "TP"),
            array('state_id' => 26, 'name' => "Tirunelveli",'code' => "TV"),
            array('state_id' => 26, 'name' => "Tirupathur",'code' => "TP"),
            array('state_id' => 26, 'name' => "Tiruppur",'code' => "TR"),
            array('state_id' => 26, 'name' => "Tiruvallur",'code' => "TV"),
            array('state_id' => 26, 'name' => "Tiruvannamalai",'code' => "TR"),
            array('state_id' => 26, 'name' => "Tiruvarur",'code' => "TR"),
            array('state_id' => 26, 'name' => "Vellore",'code' => "VE"),
            array('state_id' => 26, 'name' => "Viluppuram",'code' => "VL"),
            array('state_id' => 26, 'name' => "Virudhunagar",'code' => "VR"),
            array('state_id' => 27, 'name' => "Adilabad",'code' => ""),
            array('state_id' => 27, 'name' => "Bhadradri Kothagudem",'code' => ""),
            array('state_id' => 27, 'name' => "Hyderabad",'code' => ""),
            array('state_id' => 27, 'name' => "Jagtial",'code' => ""),
            array('state_id' => 27, 'name' => "Jangaon",'code' => ""),
            array('state_id' => 27, 'name' => "Jayashankar Bhupalpally",'code' => ""),
            array('state_id' => 27, 'name' => "Jogulamba Gadwal",'code' => ""),
            array('state_id' => 27, 'name' => "Kamareddy",'code' => ""),
            array('state_id' => 27, 'name' => "Karimnagar",'code' => ""),
            array('state_id' => 27, 'name' => "Khammam",'code' => ""),
            array('state_id' => 27, 'name' => "Kumuram Bheem",'code' => ""),
            array('state_id' => 27, 'name' => "Mahabubabad",'code' => ""),
            array('state_id' => 27, 'name' => "Mahabubnagar",'code' => ""),
            array('state_id' => 27, 'name' => "Mancherial",'code' => ""),
            array('state_id' => 27, 'name' => "Medak",'code' => ""),
            array('state_id' => 27, 'name' => "Medchal-Malkajgiri",'code' => ""),
            array('state_id' => 27, 'name' => "Mulugu",'code' => ""),
            array('state_id' => 27, 'name' => "Nagarkurnool",'code' => ""),
            array('state_id' => 27, 'name' => "Nalgonda",'code' => ""),
            array('state_id' => 27, 'name' => "Narayanpet",'code' => ""),
            array('state_id' => 27, 'name' => "Nirmal",'code' => ""),
            array('state_id' => 27, 'name' => "Nizamabad",'code' => ""),
            array('state_id' => 27, 'name' => "Peddapalli",'code' => ""),
            array('state_id' => 27, 'name' => "Rajanna Sircilla",'code' => ""),
            array('state_id' => 27, 'name' => "Ranga Reddy",'code' => ""),
            array('state_id' => 27, 'name' => "Sangareddy",'code' => ""),
            array('state_id' => 27, 'name' => "Siddipet",'code' => ""),
            array('state_id' => 27, 'name' => "Suryapet",'code' => ""),
            array('state_id' => 27, 'name' => "Vikarabad",'code' => ""),
            array('state_id' => 27, 'name' => "Wanaparthy",'code' => ""),
            array('state_id' => 27, 'name' => "Warangal Rural",'code' => ""),
            array('state_id' => 27, 'name' => "Warangal Urban",'code' => ""),
            array('state_id' => 27, 'name' => "Yadadri Bhuvanagiri",'code' => ""),
            array('state_id' => 12, 'name' => "Bagalkot",'code' => ""),
            array('state_id' => 12, 'name' => "Ballari (Bellary)",'code' => ""),
            array('state_id' => 12, 'name' => "Belagavi (Belgaum)",'code' => ""),
            array('state_id' => 12, 'name' => "Bengaluru Rural",'code' => ""),
            array('state_id' => 12, 'name' => "Bengaluru Urban (Bangalore)",'code' => ""),
            array('state_id' => 12, 'name' => "Bidar",'code' => ""),
            array('state_id' => 12, 'name' => "Chamarajanagar",'code' => ""),
            array('state_id' => 12, 'name' => "Chikballapur",'code' => ""),
            array('state_id' => 12, 'name' => "Chikkamagaluru (Chikmagalur)",'code' => ""),
            array('state_id' => 12, 'name' => "Chitradurga",'code' => ""),
            array('state_id' => 12, 'name' => "Dakshina Kannada (Mangalore)",'code' => ""),
            array('state_id' => 12, 'name' => "Davanagere",'code' => ""),
            array('state_id' => 12, 'name' => "Dharwad",'code' => ""),
            array('state_id' => 12, 'name' => "Gadag",'code' => ""),
            array('state_id' => 12, 'name' => "Hassan",'code' => ""),
            array('state_id' => 12, 'name' => "Haveri",'code' => ""),
            array('state_id' => 12, 'name' => "Kalaburagi (Gulbarga)",'code' => ""),
            array('state_id' => 12, 'name' => "Kodagu (Coorg)",'code' => ""),
            array('state_id' => 12, 'name' => "Kolar",'code' => ""),
            array('state_id' => 12, 'name' => "Koppal",'code' => ""),
            array('state_id' => 12, 'name' => "Mandya",'code' => ""),
            array('state_id' => 12, 'name' => "Mysuru (Mysore)",'code' => ""),
            array('state_id' => 12, 'name' => "Raichur",'code' => ""),
            array('state_id' => 12, 'name' => "Ramanagara",'code' => ""),
            array('state_id' => 12, 'name' => "Shivamogga (Shimoga)",'code' => ""),
            array('state_id' => 12, 'name' => "Tumakuru (Tumkur)",'code' => ""),
            array('state_id' => 12, 'name' => "Udupi",'code' => ""),
            array('state_id' => 12, 'name' => "Uttara Kannada (Karwar)",'code' => ""),
            array('state_id' => 12, 'name' => "Vijayapura (Bijapur)",'code' => ""),
            array('state_id' => 12, 'name' => "Yadgir",'code' => ""),
            array('state_id' => 1, 'name' => "Anantapur",'code' => ""),
            array('state_id' => 1, 'name' => "Chittoor",'code' => ""),
            array('state_id' => 1, 'name' => "East Godavari",'code' => ""),
            array('state_id' => 1, 'name' => "Guntur",'code' => ""),
            array('state_id' => 1, 'name' => "Kadapa (YSR Kadapa)",'code' => ""),
            array('state_id' => 1, 'name' => "Krishna",'code' => ""),
            array('state_id' => 1, 'name' => "Kurnool",'code' => ""),
            array('state_id' => 1, 'name' => "Nellore",'code' => ""),
            array('state_id' => 1, 'name' => "Prakasam",'code' => ""),
            array('state_id' => 1, 'name' => "Srikakulam",'code' => ""),
            array('state_id' => 1, 'name' => "Visakhapatnam",'code' => ""),
            array('state_id' => 1, 'name' => "Vizianagaram",'code' => ""),
            array('state_id' => 1, 'name' => "West Godavari",'code' => ""),
            array('state_id' => 32, 'name' => "Central Delhi",'code' => ""),
            array('state_id' => 32, 'name' => "East Delhi",'code' => ""),
            array('state_id' => 32, 'name' => "New Delhi",'code' => ""),
            array('state_id' => 32, 'name' => "North Delhi",'code' => ""),
            array('state_id' => 32, 'name' => "North East Delhi",'code' => ""),
            array('state_id' => 32, 'name' => "North West Delhi",'code' => ""),
            array('state_id' => 32, 'name' => "Shahdara",'code' => ""),
            array('state_id' => 32, 'name' => "South Delhi",'code' => ""),
            array('state_id' => 32, 'name' => "South East Delhi",'code' => ""),
            array('state_id' => 32, 'name' => "South West Delhi",'code' => ""),
            array('state_id' => 32, 'name' => "West Delhi",'code' => ""),
        );
        DB::table('districts')->insert($districts);
    }
}
