<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StateTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('states')->delete();
        $states = array(
            array('country_id' => 1, 'name' => "Not Specified", 'code' => "NS"),
            array('country_id' => 101, 'name' => "Andhra Pradesh", 'code' => "AD"),
            array('country_id' => 101, 'name' => "Arunachal Pradesh", 'code' => "AR"),
            array('country_id' => 101, 'name' => "Assam", 'code' => "AS"),
            array('country_id' => 101, 'name' => "Bihar", 'code' => "BR"),
            array('country_id' => 101, 'name' => "Chhattisgarh", 'code' => "CT"),
            array('country_id' => 101, 'name' => "Goa", 'code' => "GO"),
            array('country_id' => 101, 'name' => "Gujarat", 'code' => "GJ"),
            array('country_id' => 101, 'name' => "Haryana", 'code' => "HR"),
            array('country_id' => 101, 'name' => "Himachal Pradesh", 'code' => "HP"),
            array('country_id' => 101, 'name' => "Jammu and Kashmir", 'code' => "JK"),
            array('country_id' => 101, 'name' => "Jharkhand", 'code' => "JH"),
            array('country_id' => 101, 'name' => "Karnataka", 'code' => "KA"),
            array('country_id' => 101, 'name' => "Kerala", 'code' => "KL"),
            array('country_id' => 101, 'name' => "Lakshadweep Islands", 'code' => "LD"),
            array('country_id' => 101, 'name' => "Madhya Pradesh", 'code' => "MP"),
            array('country_id' => 101, 'name' => "Maharashtra", 'code' => "MH"),
            array('country_id' => 101, 'name' => "Manipur", 'code' => "MN"),
            array('country_id' => 101, 'name' => "Meghalaya", 'code' => "ML"),
            array('country_id' => 101, 'name' => "Mizoram", 'code' => "MZ"),
            array('country_id' => 101, 'name' => "Nagaland", 'code' => "NL"),
            array('country_id' => 101, 'name' => "Odisha", 'code' => "OD"),
            array('country_id' => 101, 'name' => "Pondicherry", 'code' => "PY"),
            array('country_id' => 101, 'name' => "Punjab", 'code' => "PB"),
            array('country_id' => 101, 'name' => "Rajasthan", 'code' => "RJ"),
            array('country_id' => 101, 'name' => "Sikkim", 'code' => "SK"),
            array('country_id' => 101, 'name' => "Tamil Nadu", 'code' => "TN"),
            array('country_id' => 101, 'name' => "Telangana", 'code' => "TS"),
            array('country_id' => 101, 'name' => "Tripura", 'code' => "TR"),
            array('country_id' => 101, 'name' => "Uttar Pradesh", 'code' => "UP"),
            array('country_id' => 101, 'name' => "Uttarakhand", 'code' => "UK"),
            array('country_id' => 101, 'name' => "West Bengal", 'code' => "WB"),
            array('country_id' => 101, 'name' => "Delhi", 'code' => "DL"),
            array('country_id' => 1, 'name' => "Alabama", 'code' => ""),
            array('country_id' => 1, 'name' => "Alaska", 'code' => ""),
            array('country_id' => 1, 'name' => "Arizona", 'code' => ""),
            array('country_id' => 1, 'name' => "Arkansas", 'code' => ""),
            array('country_id' => 1, 'name' => "California", 'code' => ""),
            array('country_id' => 1, 'name' => "Colorado", 'code' => ""),
            array('country_id' => 1, 'name' => "Connecticut", 'code' => ""),
            array('country_id' => 1, 'name' => "Delaware", 'code' => ""),
            array('country_id' => 1, 'name' => "Florida", 'code' => ""),
            array('country_id' => 1, 'name' => "Georgia", 'code' => ""),
            array('country_id' => 1, 'name' => "Hawaii", 'code' => ""),
            array('country_id' => 1, 'name' => "Idaho", 'code' => ""),
            array('country_id' => 1, 'name' => "Illinois", 'code' => ""),
            array('country_id' => 1, 'name' => "Indiana", 'code' => ""),
            array('country_id' => 1, 'name' => "Iowa", 'code' => ""),
            array('country_id' => 1, 'name' => "Kansas", 'code' => ""),
            array('country_id' => 1, 'name' => "Kentucky", 'code' => ""),
            array('country_id' => 1, 'name' => "Louisiana", 'code' => ""),
            array('country_id' => 1, 'name' => "Maine", 'code' => ""),
            array('country_id' => 1, 'name' => "Maryland", 'code' => ""),
            array('country_id' => 1, 'name' => "Massachusetts", 'code' => ""),
            array('country_id' => 1, 'name' => "Michigan", 'code' => ""),
            array('country_id' => 1, 'name' => "Minnesota", 'code' => ""),
            array('country_id' => 1, 'name' => "Mississippi", 'code' => ""),
            array('country_id' => 1, 'name' => "Missouri", 'code' => ""),
            array('country_id' => 1, 'name' => "Montana", 'code' => ""),
            array('country_id' => 1, 'name' => "Nebraska", 'code' => ""),
            array('country_id' => 1, 'name' => "Nevada", 'code' => ""),
            array('country_id' => 1, 'name' => "New Hampshire", 'code' => ""),
            array('country_id' => 1, 'name' => "New Jersey", 'code' => ""),
            array('country_id' => 1, 'name' => "New Mexico", 'code' => ""),
            array('country_id' => 1, 'name' => "New York", 'code' => ""),
            array('country_id' => 1, 'name' => "North Carolina", 'code' => ""),
            array('country_id' => 1, 'name' => "North Dakota", 'code' => ""),
            array('country_id' => 1, 'name' => "Ohio", 'code' => ""),
            array('country_id' => 1, 'name' => "Oklahoma", 'code' => ""),
            array('country_id' => 1, 'name' => "Oregon", 'code' => ""),
            array('country_id' => 1, 'name' => "Pennsylvania", 'code' => ""),
            array('country_id' => 1, 'name' => "Rhode Island", 'code' => ""),
            array('country_id' => 1, 'name' => "South Carolina", 'code' => ""),
            array('country_id' => 1, 'name' => "South Dakota", 'code' => ""),
            array('country_id' => 1, 'name' => "Tennessee", 'code' => ""),
            array('country_id' => 1, 'name' => "Texas", 'code' => ""),
            array('country_id' => 1, 'name' => "Utah", 'code' => ""),
            array('country_id' => 1, 'name' => "Vermont", 'code' => ""),
            array('country_id' => 1, 'name' => "Virginia", 'code' => ""),
            array('country_id' => 1, 'name' => "Washington", 'code' => ""),
            array('country_id' => 1, 'name' => "West Virginia", 'code' => ""),
            array('country_id' => 1, 'name' => "Wisconsin", 'code' => ""),
            array('country_id' => 1, 'name' => "Wyoming", 'code' => ""),
            array('country_id' => 2, 'name' => "Alberta", 'code' => ""),
            array('country_id' => 2, 'name' => "British Columbia", 'code' => ""),
            array('country_id' => 2, 'name' => "Manitoba", 'code' => ""),
            array('country_id' => 2, 'name' => "New Brunswick", 'code' => ""),
            array('country_id' => 2, 'name' => "Newfoundland and Labrador", 'code' => ""),
            array('country_id' => 2, 'name' => "Northwest Territories", 'code' => ""),
            array('country_id' => 2, 'name' => "Nova Scotia", 'code' => ""),
            array('country_id' => 2, 'name' => "Nunavut", 'code' => ""),
            array('country_id' => 2, 'name' => "Ontario", 'code' => ""),
            array('country_id' => 2, 'name' => "Prince Edward Island", 'code' => ""),
            array('country_id' => 2, 'name' => "Quebec", 'code' => ""),
            array('country_id' => 2, 'name' => "Saskatchewan", 'code' => ""),
            array('country_id' => 2, 'name' => "Yukon", 'code' => ""),
            array('country_id' => 15, 'name' => "Australian Capital Territory", 'code' => ""),
            array('country_id' => 15, 'name' => "New South Wales", 'code' => ""),
            array('country_id' => 15, 'name' => "Northern Territory", 'code' => ""),
            array('country_id' => 15, 'name' => "Queensland", 'code' => ""),
            array('country_id' => 15, 'name' => "South Australia", 'code' => ""),
            array('country_id' => 15, 'name' => "Tasmania", 'code' => ""),
            array('country_id' => 15, 'name' => "Victoria", 'code' => ""),
            array('country_id' => 15, 'name' => "Western Australia", 'code' => ""),
            array('country_id' => 15, 'name' => "England", 'code' => ""),
            array('country_id' => 15, 'name' => "Scotland", 'code' => ""),
            array('country_id' => 15, 'name' => "Wales", 'code' => ""),
            array('country_id' => 15, 'name' => "Northern Ireland", 'code' => ""),
            array('country_id' => 104, 'name' => "Connacht", 'code' => ""),
            array('country_id' => 104, 'name' => "Leinster", 'code' => ""),
            array('country_id' => 104, 'name' => "Munster", 'code' => ""),
            array('country_id' => 104, 'name' => "Ulster", 'code' => ""),
            array('country_id' => 104, 'name' => "Dublin", 'code' => ""),
            array('country_id' => 106, 'name' => "Abruzzo", 'code' => ""),
            array('country_id' => 106, 'name' => "Basilicata", 'code' => ""),
            array('country_id' => 106, 'name' => "Calabria", 'code' => ""),
            array('country_id' => 106, 'name' => "Campania", 'code' => ""),
            array('country_id' => 106, 'name' => "Emilia-Romagna", 'code' => ""),
            array('country_id' => 106, 'name' => "Friuli-Venezia Giulia", 'code' => ""),
            array('country_id' => 106, 'name' => "Lazio", 'code' => ""),
            array('country_id' => 106, 'name' => "Liguria", 'code' => ""),
            array('country_id' => 106, 'name' => "Lombardy", 'code' => ""),
            array('country_id' => 106, 'name' => "Marche", 'code' => ""),
            array('country_id' => 106, 'name' => "Molise", 'code' => ""),
            array('country_id' => 106, 'name' => "Piedmont", 'code' => ""),
            array('country_id' => 106, 'name' => "Apulia", 'code' => ""),
            array('country_id' => 106, 'name' => "Sardinia", 'code' => ""),
            array('country_id' => 106, 'name' => "Sicily", 'code' => ""),
            array('country_id' => 106, 'name' => "Trentino-Alto Adige/Südtirol", 'code' => ""),
            array('country_id' => 106, 'name' => "Tuscany", 'code' => ""),
            array('country_id' => 106, 'name' => "Umbria", 'code' => ""),
            array('country_id' => 106, 'name' => "Aosta Valley", 'code' => ""),
            array('country_id' => 106, 'name' => "Veneto", 'code' => ""),
            array('country_id' => 74, 'name' => "Auvergne-Rhône-Alpes", 'code' => ""),
            array('country_id' => 74, 'name' => "Bourgogne-Franche-Comté", 'code' => ""),
            array('country_id' => 74, 'name' => "Brittany", 'code' => ""),
            array('country_id' => 74, 'name' => "Centre-Val de Loire", 'code' => ""),
            array('country_id' => 74, 'name' => "Corsica", 'code' => ""),
            array('country_id' => 74, 'name' => "Grand Est", 'code' => ""),
            array('country_id' => 74, 'name' => "Hauts-de-France", 'code' => ""),
            array('country_id' => 74, 'name' => "Île-de-France", 'code' => ""),
            array('country_id' => 74, 'name' => "Normandy", 'code' => ""),
            array('country_id' => 74, 'name' => "Nouvelle-Aquitaine", 'code' => ""),
            array('country_id' => 74, 'name' => "Occitanie", 'code' => ""),
            array('country_id' => 74, 'name' => "Pays de la Loire", 'code' => ""),
            array('country_id' => 74, 'name' => "Provence-Alpes-Côte d'Azur", 'code' => ""),
            array('country_id' => 74, 'name' => "Guadeloupe", 'code' => ""),
            array('country_id' => 74, 'name' => "Martinique", 'code' => ""),
            array('country_id' => 74, 'name' => "French Guiana", 'code' => ""),
            array('country_id' => 74, 'name' => "Réunion", 'code' => ""),
            array('country_id' => 74, 'name' => "Mayotte", 'code' => ""),
            array('country_id' => 155, 'name' => "Northland", 'code' => ""),
            array('country_id' => 155, 'name' => "Auckland", 'code' => ""),
            array('country_id' => 155, 'name' => "Waikato", 'code' => ""),
            array('country_id' => 155, 'name' => "Bay of Plenty", 'code' => ""),
            array('country_id' => 155, 'name' => "Gisborne", 'code' => ""),
            array('country_id' => 155, 'name' => "Hawke's Bay", 'code' => ""),
            array('country_id' => 155, 'name' => "Taranaki", 'code' => ""),
            array('country_id' => 155, 'name' => "Manawatū-Whanganui", 'code' => ""),
            array('country_id' => 155, 'name' => "Wellington", 'code' => ""),
            array('country_id' => 155, 'name' => "Tasman", 'code' => ""),
            array('country_id' => 155, 'name' => "Nelson", 'code' => ""),
            array('country_id' => 155, 'name' => "Marlborough", 'code' => ""),
            array('country_id' => 155, 'name' => "West Coast", 'code' => ""),
            array('country_id' => 155, 'name' => "Canterbury", 'code' => ""),
            array('country_id' => 155, 'name' => "Otago", 'code' => ""),
            array('country_id' => 155, 'name' => "Southland", 'code' => ""),
            array('country_id' => 82, 'name' => "Baden-Württemberg", 'code' => ""),
            array('country_id' => 82, 'name' => "Bavaria", 'code' => ""),
            array('country_id' => 82, 'name' => "Berlin", 'code' => ""),
            array('country_id' => 82, 'name' => "Brandenburg", 'code' => ""),
            array('country_id' => 82, 'name' => "Bremen", 'code' => ""),
            array('country_id' => 82, 'name' => "Hamburg", 'code' => ""),
            array('country_id' => 82, 'name' => "Hesse", 'code' => ""),
            array('country_id' => 82, 'name' => "Mecklenburg-Vorpommern", 'code' => ""),
            array('country_id' => 82, 'name' => "Lower Saxony", 'code' => ""),
            array('country_id' => 82, 'name' => "North Rhine-Westphalia", 'code' => ""),
            array('country_id' => 82, 'name' => "Rhineland-Palatinate", 'code' => ""),
            array('country_id' => 82, 'name' => "Saarland", 'code' => ""),
            array('country_id' => 82, 'name' => "Saxony", 'code' => ""),
            array('country_id' => 82, 'name' => "Saxony-Anhalt", 'code' => ""),
            array('country_id' => 82, 'name' => "Schleswig-Holstein", 'code' => ""),
            array('country_id' => 82, 'name' => "Thuringia", 'code' => ""),
            array('country_id' => 82, 'name' => "Thuringia", 'code' => ""),
        );
        DB::table('states')->insert($states);
    }
}
